// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  r_ich_text: dynamic(() => import("./RichText")),
  text_image: dynamic(() => import("./TextImage")),
};
